# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 549b0421fd80248289c6d050427585acccb87f8e01de56a06ac48cb23923d45c6b4a94b489d667601041af180c59877d45128e50621ac8d905f1a5619b8c7338

test:
  secret_key_base: 7bbd4b2838b0a4654817070a74842b13fc1f74583c330ff54111fe551b53f6beb82a5cec31650035d2212f4b6a0cc6e827cd32d3dfd44ce34d90272f4c8fe4ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
